version: '3.8'

networks:
  meteo_network:

services:
  api:
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - OPEN_METEO_BASE_URL=${OPEN_METEO_BASE_URL}
    depends_on:
      - db
    networks:
      - meteo_network

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    networks:
      - meteo_network

volumes:
  mariadb_data: