name: Run Pytest on Push to Production

on:
  push:
    branches:
      - production

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          docker-compose up -d db
          docker-compose up -d api
          sleep 15

      - name: Check if API server is running
        run: |
          curl --fail http://127.0.0.1:8000 || (echo "API server is not running" && exit 1)

      - name: Run tests
        run: |
          docker-compose exec api pytest